### ISSUE TITLE
about "ckpt_path" and "data_path" for running the code

### ISSUE THREAD

**Issue by zhongyi-zhou** [ArantxaCasanova/ralis#1]
Hi! I am currently working in a similar field and I'm really excited to find this project.

I find I cannot run the code probably due to these two variables:
https://github.com/ArantxaCasanova/ralis/blob/83325f318621b2b856a91cf1b26d1d16e4558657/scripts/launch_train_ralis.sh#L3-L4

I have tried replacing the following code into the path of the model you provided in google drive, it seems not working.
```
ckpt_path='/home/casanova/scratch/ckpt_seg'
```

Also, could you briefly introduce how ```data_path``` works in the project? It seems that the python file does not use this argument.

**Comment by ArantxaCasanova** [comment]
Hi, 
you have to replace `data_path` by the path that you downloaded your datasets into. The datasets need to be saved in a structure such as this one:
` <data_path>/datasets/camvid`
`<data_path>/datasets/gta5 `
`<data_path>/datasets/cityscapes `
(Note that you only need to download the datasets you are going to use).

With respect to `ckpt_path`, it is the path where you have saved the downloaded models. Following the structure of the pretrained models I provided, let's put an example:
`user_name/ralis/cs/<exp_name>`
In this case, `ckpt_path='user_name/ralis/cs'`. 

Additionally, you will use the experiment name  (`--exp-name <exp_name>`) in the scripts. `exp_name` will be the name of the folder where your experiment will be saved. You can run this with `launch_test_ralis.sh`. In this folder, you will save the weights of the segmentation model trained on data that RALIS feeds it with its active learning policy.
For the other variables, `exp-name-toload` is name of the pretrained network for the segmentation network on GTA5 (also provided in the pretrained models), and `exp-name-toload-rl` is the name of the already trained RALIS model, in case you want to test it and train a segmentation network with it. 

The script does use the `data_path` argument. More specifically, you can find it [here](https://github.com/ArantxaCasanova/ralis/blob/83325f318621b2b856a91cf1b26d1d16e4558657/run.py#L82).

**Comment by Payden-McBee** [comment]
Hey I'm trying to run your code and then apply it on a medical segmentation problem. Do you show how you download the gta5 data?
