### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by Payden-McBee** [ArantxaCasanova/ralis#2]
Hello! I'm having trouble extracting the files for the pretrained models. I can download the ralis_models.gz file, but when I unzip it, there is only a file called ralis_models with no extensions. Are you able to download it, gunzip ralis_models.gz, and get the correct folder out?

**Comment by Payden-McBee** [comment]
I couldn't get it to work from the command line, but I was able  to unzip the file from the gui on my linux vm (my windows machine wouldn't cooperate).

**Comment by yuxuanxu-pku** [comment]
hello could you tell the details of unzipping the file from the gui on my linux vm cause i still couldnot get the pth files by gunzip command on my linux machine (ubuntu os)
