### ISSUE TITLE
Run Time

### ISSUE THREAD

**Issue by Payden-McBee** [ArantxaCasanova/ralis#3]
Could you give a ballpark on how long the training took and what kind of hardware you used? I ran the baseline shell script for CAMVID only with 2 GPUs and timed out after 24 hours, and I was curious how long to try running it.

**Comment by ArantxaCasanova** [comment]
If I remember correctly, I was using 1 GPU (16GB). The baseline on CAMVID shouldn't take more than a few days. It will depend on the budget (number of crops selected by the active learning algorithm) you are using, as well as the baseline AL method. Random and entropy should be pretty fast, but BALD can multiply your run time significantly.

**Comment by cherryolg** [comment]
Which file you run, run.py or train_supervised？
